# Generated by Django 3.1.7 on 2021-03-23 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezka', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='number_of_fans_rate',
            field=models.PositiveIntegerField(verbose_name='Количество оценок зрителей'),
        ),
    ]
