# Generated by Django 3.1.7 on 2021-03-23 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rezka', '0002_auto_20210323_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='films',
            name='year',
        ),
    ]
