# Generated by Django 3.1.7 on 2021-03-23 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezka', '0003_remove_films_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='year',
            field=models.IntegerField(default=1, verbose_name='Год выпуска'),
        ),
    ]
