# Generated by Django 3.1.7 on 2021-03-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezka', '0004_films_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='image_url',
            field=models.CharField(max_length=200, verbose_name='Ссылка на картинку'),
        ),
        migrations.AlterField(
            model_name='films',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название фильма'),
        ),
        migrations.AlterField(
            model_name='films',
            name='url',
            field=models.CharField(max_length=200, verbose_name='Ссылка на фильм'),
        ),
    ]
